name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint:
    uses: LegionForge/dev-rig/.github/workflows/rust-lint.yml@a68806c4f52c3cf3cf49b05733b0f8fee73214af

  test:
    uses: LegionForge/dev-rig/.github/workflows/rust-test.yml@a68806c4f52c3cf3cf49b05733b0f8fee73214af

  sast:
    uses: LegionForge/dev-rig/.github/workflows/rust-sast.yml@a68806c4f52c3cf3cf49b05733b0f8fee73214af
    with:
      source-dirs: "src"
    permissions:
      contents: read
      security-events: write
      actions: read       # required by the nested codeql job

  audit:
    uses: LegionForge/dev-rig/.github/workflows/rust-audit.yml@a68806c4f52c3cf3cf49b05733b0f8fee73214af

  secrets:
    uses: LegionForge/dev-rig/.github/workflows/secrets.yml@a68806c4f52c3cf3cf49b05733b0f8fee73214af
    permissions:
      contents: read

  sbom:
    uses: LegionForge/dev-rig/.github/workflows/rust-sbom.yml@a68806c4f52c3cf3cf49b05733b0f8fee73214af

  trivy:
    uses: LegionForge/dev-rig/.github/workflows/trivy.yml@a68806c4f52c3cf3cf49b05733b0f8fee73214af
    permissions:
      security-events: write
      contents: read
